# Generated by Django 2.1.2 on 2018-12-01 05:18

from django.db import models, migrations
from django.contrib.auth.models import Group
from ..models import Course, Staff


def add_group_permissions(app,schema_editor):
    #Admin
    group, created = Group.objects.get_or_create(name='Administrator')   
    if created:
                        
        group.permissions.add(can_create_course,can_edit_course,can_delete_course,can_view_course,
        can_create_section,can_edit_section,can_delete_section,can_view_section,can_create_user,can_edit_user,can_edit_self,
        can_delete_user,can_view_user,can_view_private,can_email_all)
        logger.info('Admin Group created')

    #Supervisor
    group, created = Group.objects.get_or_create(name='Supervisor') 
    if created:
        group.permissions.add(can_create_course,can_edit_course,can_delete_course,can_view_course,
        can_create_section,can_edit_section,can_delete_section,can_view_section,can_create_user,can_edit_user,can_edit_self,
        can_delete_user,can_view_user,can_view_private,can_email_all,can_assign_ta,can_assign_ins)
        logger.info('Supervisor Group created')

    #Instructor
    group, created = Group.objects.get_or_create(name='Instructor') 
    if created:
        group.permissions.add(can_view_course,can_edit_self,can_view_user,can_view_private,can_assign_ta,can_email_tas)
        logger.info('Instructor Group created')

    #TA
    group, created = Group.objects.get_or_create(name='TA') 
    if created:
        group.permissions.add(Staff.can_view_course,Staff.can_view_section,Staff.can_edit_self,Staff.can_view_user)
        logger.info('Instructor Group created')    


class Migration(migrations.Migration):

    dependencies = [
        ('TAServer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
