# Generated by Django 2.1.2 on 2018-12-01 05:18

from django.db import models, migrations
from django.contrib.auth.models import Group, Permission
from ..models import Course, Staff, Section


def add_group_permissions(app,schema_editor):


    #Admin
    group, created = Group.objects.get_or_create(name='Administrator')   
    if created:
                        
        # group.permissions.add(Course.can_create_course,Course.can_edit_course,Course.can_delete_course,Course.can_view_course,
        # Section.can_create_section,Section.can_edit_section,Section.can_delete_section,Section.can_view_section,Staff.can_create_user,Staff.can_edit_user,Staff.can_edit_self,
        # Staff.can_delete_user,Staff.can_view_user,Staff.can_view_private,Staff.can_email_all)
        print('Admin Group created')

    #Supervisor
    group, created = Group.objects.get_or_create(name='Supervisor') 
    if created:
        # group.permissions.add(Course.can_create_course,Course.can_edit_course,Course.can_delete_course,Course.can_view_course,
        # Section.can_create_section,Section.can_edit_section,Section.can_delete_section,Section.can_view_section,Staff.can_create_user,Staff.can_edit_user,Staff.can_edit_self,
        # Staff.can_delete_user,Staff.can_view_user,Staff.can_view_private,Staff.can_email_all,Staff.can_assign_ta,Staff.can_assign_ins)
        print('Supervisor Group created')

    #Instructor
    group, created = Group.objects.get_or_create(name='Instructor') 
    if created:
        # group.permissions.add(Course.can_view_course,Staff.can_edit_self,Staff.can_view_user,Staff.can_view_private,Staff.can_assign_ta,Staff.can_email_tas)
        print('Instructor Group created')

    #TA
    group, created = Group.objects.get_or_create(name='TA') 
    if created:
        #group.permissions.add(can_view_course,Section.can_view_section,Staff.can_edit_self,Staff.can_view_user)
        print('Instructor Group created')    


class Migration(migrations.Migration):

    dependencies = [
        ('TAServer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
