# Generated by Django 2.1.2 on 2018-12-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAServer', '0002_auto_20181201_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_create_course', 'Can create courses'), ('can_edit_course', 'Can edit courses'), ('can_delete_course', 'Can delete courses'), ('can_view_course', 'Can view courses')),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_create_section', 'Can create sections'), ('can_edit_section', 'Can edit sections'), ('can_delete_section', 'Can delete sections'), ('can_view_section', 'Can view sections')),
            },
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': (('can_create_user', 'Can create users'), ('can_edit_user', 'Can edit users'), ('can_edit_self', 'Can edit users'), ('can_delete_user', 'Can delete users'), ('can_view_user', 'Can view users'), ('can_view_private', 'Can view private user data'), ('can_email_all', 'Can send emails to all users'), ('can_assign_ta', "Can assign TA's"), ('can_assign_ins', 'Can assign instructors'), ('can_email_tas', 'Can send emails'))},
        ),
    ]
